services:
  # --- Seafile (server + DB + cache) ---
  seafile-db:
    image: mariadb:10.11
    container_name: seafile-db
    restart: unless-stopped
    hostname: seafile-db
    environment:
      SEAFILE_MYSQL_DB_USER: ${SEAFILE_MYSQL_DB_USER}
      MYSQL_ROOT_PASSWORD: ${INIT_SEAFILE_MYSQL_ROOT_PASSWORD}
      MYSQL_LOG_CONSOLE: "true"
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - /mnt/media/cloud/seafile/db:/var/lib/mysql
    networks:
      - proxy_network

  seafile-memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    restart: unless-stopped
    networks:
      proxy_network:
        aliases: 
          - memcached

  seafile:
    image: seafileltd/seafile-mc:13.0.15
    container_name: seafile
    restart: unless-stopped
    depends_on:
      - seafile-db
      - seafile-memcached
    volumes:
      - /mnt/media/cloud/seafile/data:/shared
    environment:
      SEAFILE_MYSQL_DB_HOST: ${SEAFILE_MYSQL_DB_HOST}
      SEAFILE_MYSQL_DB_PORT: "${SEAFILE_MYSQL_DB_PORT}"
      SEAFILE_MYSQL_DB_USER: ${SEAFILE_MYSQL_DB_USER}
      SEAFILE_MYSQL_DB_CCNET_DB_NAME: ${SEAFILE_MYSQL_DB_CCNET_DB_NAME}
      SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: ${SEAFILE_MYSQL_DB_SEAFILE_DB_NAME}
      SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: ${SEAFILE_MYSQL_DB_SEAHUB_DB_NAME}
      INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ${INIT_SEAFILE_MYSQL_ROOT_PASSWORD}
      SEAFILE_MYSQL_DB_PASSWORD: ${SEAFILE_MYSQL_DB_PASSWORD}
      INIT_SEAFILE_ADMIN_EMAIL: ${INIT_SEAFILE_ADMIN_EMAIL}
      INIT_SEAFILE_ADMIN_PASSWORD: ${INIT_SEAFILE_ADMIN_PASSWORD}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      SEAFILE_SERVER_HOSTNAME: ${SEAFILE_SERVER_HOSTNAME}

      
      #INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ${SEAFILE_DB_ROOT_PASSWORD}
      #SEAFILE_ADMIN_EMAIL: ${SEAFILE_ADMIN_EMAIL}
      #SEAFILE_ADMIN_PASSWORD: ${SEAFILE_ADMIN_PASSWORD}
      #SEAFILE_SERVER_HOSTNAME: ${SEAFILE_SERVER_HOSTNAME}
      # If running behind HTTPS reverse proxy, you may also want:
      SEAFILE_SERVER_LETSENCRYPT: false 
      FORCE_HTTPS_IN_CONF: false
      #
    networks:
      - proxy_network

networks:
  proxy_network: 
    external: true
