services:
  nextcloud-database:
    image: mariadb:11.3
    container_name: nextcloud-database
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - /mnt/media/nextcloud/db:/var/lib/mysql
    env_file:
      - nextcloud.env
    networks:
      - proxy_network
  

  nextcloud-redis:
    image: redis:7.2.4
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass fMHtAdH766suqiB
    networks:
      - proxy_network
   
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    links:
      - nextcloud-database
      - nextcloud-redis
    ports:
      - 8080:80
    volumes:
      # - /mnt/media/nextcloud/root:/var/www/html
      - /mnt/media/nextcloud/config:/config
      - /mnt/media/nextcloud/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_HOST=nextcloud-database
      - REDIS_HOST_PASSWORD=fMHtAdH766suqiB
    env_file:
      - nextcloud.env

    networks:
      - proxy_network
    depends_on:
      - nextcloud-database
      - nextcloud-redis
      
networks:
  proxy_network:
    name: proxy_network
    external: true
