---
services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '${NPM_IP:-192.168.0.197}:80:80' # Public HTTP Port
      - '${NPM_IP:-192.168.0.197}:443:443' # Public HTTPS Port
      - '${NPM_IP:-192.168.0.197}:81:81' # Admin Web Port
    volumes:
      - ${CONFIG_PATH:-/opt/docker}/proxy/data:/data
      - ${CONFIG_PATH:-/opt/docker}/proxy/letsencrypt:/etc/letsencrypt
    networks:
      - pihole
      - proxy_network
      - apptjc_proxy_network
      - radarr_network
    
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "${PIHOLE_IP:-192.168.0.198}:80:80/tcp"
      - "${PIHOLE_IP:-192.168.0.198}:443:443/tcp"
      - "${PIHOLE_IP:-192.168.0.198}:53:53/tcp"
      - "${PIHOLE_IP:-192.168.0.198}:53:53/udp"
    environment:
      TZ: ${TZ:-Europe/Lisbon}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped


  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    volumes:
      - ./openvpn-data:/etc/openvpn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  ddns-updater:
    image: qmcgaw/ddns-updater:latest
    container_name: ddns-updater
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Lisbon}
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - CONFIG={"settings":[{"provider":"duckdns","domain":"${DUCKDNS_DOMAIN}","token":"${DUCKDNS_TOKEN}","ip_version":"ipv4"}]}
    volumes:
      - ./ddns/data:/updater/data
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  pihole:
  proxy_network:
    external: true
  apptjc_proxy_network:
    external: true
  radarr_network:
    external: true
