---
services:
  npm:
    container_name: npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - /opt/docker/proxy/data:/data
      - /opt/docker/proxy/letsencrypt:/etc/letsencrypt
    networks:
      npm_zbridge:
        ipv4_address: 192.168.100.10
        priority: 900
      npm_network:
        ipv4_address: 192.168.0.197
        priority: 1000
      nextcloud_network:
      proxy_network: 
    
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    privileged: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # - "80:80/tcp"
    environment:
      TZ: 'Lisbon/London'
      WEBPASSWORD: 'tuscany'
      DNSMASQ_LISTENING: local
    # Volumes store your data between container upgrades
    volumes:
      - '/opt/docker/proxy/pihole:/etc/pihole'
      - '/opt/docker/proxy/pihole/dnsmasq.d:/etc/dnsmasq.d'
    networks:
     npm_network:
       ipv4_address: 192.168.101.198
    #cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

networks:
  npm_zbridge:
    name: npm_zbridge
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
          ip_range: 192.168.100.0/24
  npm_network:
    name: npm_network
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.0.0/24
          ip_range: 192.168.0.0/24
          gateway: 192.168.0.1
  nextcloud_network:
    external: true
    name: nextcloud_network
  proxy_network:
    external: true
    name: proxy_network

